---
services:
  ovoenergy:
    build: .
    restart: unless-stopped
    ports:
      - target: 9170
        published: 9170
        protocol: tcp
    volumes:
      - type: volume
        source: ovoenergy-data
        target: /data/ovoenergy

volumes:
  ovoenergy-data: {}
